### ISSUE TITLE
game.js, data should not be defined in the onload function, but up in the hash

### ISSUE THREAD

**Issue by agmcleod** [melonjs/tutorial-platformer#11]
https://github.com/melonjs/tutorial/blob/gh-pages/index.html#L183

That should be up one scope level. I haven't checked the various steps to see how they are.

**Comment by parasyte** [comment]
Looks like a bad copy-paste from commit https://github.com/melonjs/tutorial/commit/6aae012d5dd07118d1ac828aec701162f722872b -- and I even missed it in my review! ;(

This is now fixed with the above commit.

**Comment by agmcleod** [comment]
The tutorial uses `me.game.score`, much like i mentioned in the boilerplate. I think the data hash still needs to stick around, and the tutorial should be updated to reflect. I have no problem going through it, just want to be certain I'm right on these changes first.

**Comment by parasyte** [comment]
That's really odd. `me.game` is a namespace reserved for melonJS. I don't think we want to encourage users to place arbitrary data there.

Boilerplate uses `game.data.score`, as expected: https://github.com/melonjs/boilerplate/blob/master/js/entities/HUD.js#L60-61

Tutorial is suggesting the wrong namespace, though: https://github.com/melonjs/tutorial/blob/9f55e4435158e3eadbd02d4db0ec46c54011f517/index.html#L1064-1065

That's an additional issue which I was not aware of. What I removed in the patch is a piece of JSON data appearing inside a function. (Invalid JS syntax) This was also reported by a user on the forum: https://groups.google.com/d/msg/melonjs/A8AYHCHY60Q/q5DzQJtXHDkJ As you can see here (and in the HTML itself) the data is already correctly defined, and then later incorrectly defined in the wrong location. That's what was removed.

**Comment by agmcleod** [comment]
Yeah i saw the correction on the website, thought you didnt add it back, the diff confused me :).

Also saw the me.game.score when i looked, hence why i brought it up.

**Comment by parasyte** [comment]
@agmcleod It was already there. ;) No need to add another.

Added in: https://github.com/melonjs/tutorial/commit/a9f1b5e9d3439fe270f95b835e0d7f1f8e43484b

**Comment by agmcleod** [comment]
oh lol. Not sure how i missed it then :)
