### ISSUE TITLE
Tutorial never tells the user to change the boilerplate state.change

### ISSUE THREAD

**Issue by lunarcloud** [melonjs/tutorial-platformer#12]
It's by default 

```
    me.state.change(me.state.MENU);
```

but it needs to be:

```
    me.state.change(me.state.PLAY);
```

and although the example code shows it as the correct way, people following the tutorial may miss this and never have the basic level load for them "mysteriously".

**Comment by parasyte** [comment]
[Part 9](http://melonjs.github.io/tutorial/#part9) explains the process of switching to the MENU state. So I imagine the tutorial is fine, but the boilerplate differs in this regard?

Or we could put a placeholder title screen in... :)

**Comment by obiot** [comment]
https://github.com/melonjs/boilerplate/commit/b634493585cbbbc3e770068eb938ec0696cd086e
