### ISSUE TITLE
tutorial format revamping

### ISSUE THREAD

**Issue by obiot** [melonjs/tutorial-platformer#15]
if anyone is super motivated, the following format would be great :
http://haxeflixel.com/documentation/tutorials/

**Comment by Dakkers** [comment]
I'd be interested in doing it, assuming someone doesn't beat me to it.

**Comment by obiot** [comment]
I'm first updating the tutorial to be complianr with 1.1.0, so i would suggest then to wait for the update to be ready :)

**Comment by Dakkers** [comment]
sure thing! that gives me time to complete it.

**Comment by Dakkers** [comment]
@obiot I was thinking of working on this very soon (i.e. sometime this week). are you going to be updating the code in the near future, or is it safe for me to fork and work on it?

**Comment by obiot** [comment]
Totally safe, the only potential changes are small fixes following the 2.0.0 update :)

**Comment by Dakkers** [comment]
cool, I'll be working on it tomorrow. is it cool if it's a complete rewrite? also, do you guys want it to be a single page, or separate files?

**Comment by obiot** [comment]
Actually our "wish" was to have the tutorial more following the platformer example, rather than the current tutorial, so yes rather a rewrite :)

In terms of single page or not, maybe if we can manage to make it more simple in terms of explanation i would personnaly go for one page but with some markup/tags :)

**Comment by Dakkers** [comment]
sorry, do you mean rewrite the game that is created in the tutorial, or just the layout of the tutorial? or both? I'm only planning on working on recreating the layout like http://haxeflixel.com/documentation/part-i-setup/

**Comment by obiot** [comment]
Both, with a more simple final result ? (That would more match the platformer example in the repository)

**Comment by Dakkers** [comment]
okay, sure thing. I'll start on the layout first.
