### ISSUE TITLE
Project boilerplate 

### ISSUE THREAD

**Issue by obiot** [melonjs/tutorial-platformer#3]
@parasyte 
Hi!

That's something quite trendy recently as everybody is providing a "boilerplate" for everything and it could be a good idea to propose the same for melonJS. As you were saying people will took some of their habit through the tutorial, and we could then use it in the turorial to avoid this (at least for a few stuff)

So I was thinking about creating its own "boilerplate" repo where we can define :
- a proper HTML template (instead of the crappy one that comes with the tutorial)
- a proper directory structure (that will help when people submit their code through the forum)
- add a simple project skeleton ( ~hello world)
- some default options that would be enabled in the basic project skeleton itself (auto-scaling,  debugPanel, ??)
- specific mobile options enabled in the HTML/CSS

What do you think ? I saw that you also have one on your side for your own projects, I was thinking that a lighter version of it, might be a good starting point :)

**Comment by parasyte** [comment]
Yep ! Definitely something to consider. My [template repo](https://github.com/blipjoy/template) has a lot of the same goals. All available under the MIT license, so feel free to use it however you like!

**Comment by obiot** [comment]
@see https://github.com/melonjs/boilerplate

closing this one.
