### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by tomayajapan** [melonjs/tutorial-platformer#33]
i had try this tutorial but really not working, and this tutorial is not helpful, so many missing, like resources.js is not inside the boilerplate, im new for this thing, can someone help me here? can i get a complete file that working?, im using chrome, and already create shortcut to chrome with addition -allow-file-access-from-files, still not working, i even cannot show a picture with this boilerplate :(

**Comment by obiot** [comment]
there are no missing files, this is automatically when using the boilerplate as instructed in the [README](https://github.com/melonjs/boilerplate)

not the last sentence of part one :
> To finish, let's save our new map as "area01" under the "/data/map/" folder (t**he Grunt task for building the resources.js file** will check only this specific location for maps), and we are done with the first step!
