### ISSUE TITLE
Player jumping code does not match between sections 3 and 5

### ISSUE THREAD

**Issue by Hectate** [melonjs/tutorial-platformer#36]
In "Part 3: Add a main player" the jumping code for the player entity is created, and it does not match the code later in the tutoral at the end of "Part 5: Adding some basic objects and enemies". Specifically, the following lines in Part 5 are undocumented as to their purpose or why it was changed from the previous entry:
`
      this.body.vel.y = -this.body.maxVel.y * me.timer.tick;
`
and 
`
      this.body.jumping = true;
`
I assume there was an update to the preferred jumping code that was missed in the earlier section.

I note that primarily, I was trying to figure out what set ``jumping`` to ``true`` because it's not a setter, but it appears there is not one for it so it is just set upon jumping anyway. Is this correct?

**Comment by obiot** [comment]
thanks !
