### ISSUE TITLE
Can't start boilerplate-master

### ISSUE THREAD

**Issue by emanual4real** [melonjs/tutorial-platformer#39]
I downloaded the boilerplate-master.  `npm i` then `npm run serve` and I get the below error.

```
Done.
Loading "asar.js" tasks...ERROR
>> ReferenceError: primordials is not defined
```

vs code
node 14.15.0

Best I can tell is that it is related to Grunt which I'm not familiar with.

Appreciate any help; would love to try out your framework.

**Comment by obiot** [comment]
this boilerplate is deprecated and replaced with a new es6 webpack based one : https://github.com/melonjs/es6-boilerplate
tutorial has been updated as well to reflect that
