### ISSUE TITLE
don't waste your time at THIS

### ISSUE THREAD

**Issue by SpyrariSpagetify** [melonjs/tutorial-platformer#45]
As expected, the manual is garbage, where the code in the working example and in the "platformer guide" are very different.

At the moment the PlayerEnttity is added, the onload() function is taken from nowhere. It turns out that it needs to be inserted into index.js, which in the working example of game.js and GENERALLY has a different logic.

I've ported the code from the working example (10.1) to boilerplate 10.5.2 - complete bullshit and go to hell.

The player is also not displayed, but the camera has gone astray and shows the entire map. Why? Methods from me. modules are also registered, the difference is in versions (but both are 10+) and possibly tiled settings (which are also outdated or trash in the manual)

The camera is not there, the player is not displayed + the assembly of the "npm run dev" is too long now. There is clearly something wrong, but my project is clean!

full garbage, I'd rather spend time on react or unity

Separately, I will praise the trash API, where the "dynamic" search works on the same crooked framework and every other time.

**Comment by obiot** [comment]
you use the wrong boilerplate obviously, not sure how but anyway, based on your behaviour, just go indeed to unity instead of using this trash of code. oh not to worry, you won't be missed
