### ISSUE TITLE
Tutorial rewording

### ISSUE THREAD

**Issue by parasyte** [melonjs/tutorial-platformer#8]
from @shixish via https://github.com/melonjs/melonJS/issues/259

The tutorial here:
http://melonjs.github.io/tutorial/
... in part 6 says:
"And display it when we start a new game :"
Then displays a section of code. It's not clear where this code should go. I was getting a "null is not an object" error.

I had to look at the final source to discover that it's supposed to go in the play.js file. A comment in this section would be really helpful.

Thanks for the nice library. :)

**Comment by obiot** [comment]
hi, thanks for the report, i'll see how to translate this into the new tutorial version based on the `me,EntityContainer` for the the HUD (since it's part 6)

**Comment by obiot** [comment]
this was addressed as well with the last update, so closing this one too.

thank you again for the feedback !
